INSERT INTO USUARIO(EMAIL, SENHA, MOMENTO_DO_CADASTRO) VALUES('thiago@gmail.com', '$2a$10$KvDF526I4e8j.x2hzMM1mOu/dba5aEzoE0b6zRXfTvMpRYADcM1py', CURRENT_TIMESTAMP);
INSERT INTO USUARIO(EMAIL, SENHA, MOMENTO_DO_CADASTRO) VALUES('usuario@gmail.com', '$2a$10$KvDF526I4e8j.x2hzMM1mOu/dba5aEzoE0b6zRXfTvMpRYADcM1py', CURRENT_TIMESTAMP);

INSERT INTO CATEGORIA(NOME, CATEGORIA_MAE_ID) VALUES ('Primeira Categoria', null)